### ISSUE TITLE
version 4.0 does not appear to be working (checked as of May3,2023)

### ISSUE THREAD

**Issue by SamuelLanders** [StrayEddy/GodotPlugin-MeshBuilder#19]
I am running Godot v4.0.2.stable.official [7a0977ce2]
and have your plugin placed into a fresh new instance. Attempting to activate the plugin gives this error, any ideas? :

Unable to load addon script from path: 'res://addons/meshbuilder/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/meshbuilder/plugin.cfg' to prevent further errors.

**Comment by SamuelLanders** [comment]
Examining some of the code of your plugin I am getting error notices about code out of order. specific instances are:

on the mesh_builder.gd
the 
@icon("res://addons/meshbuilder/mesh_builder/icon.svg")
is required to be above the extends statement

line 48 gives the error: Could not resolve class "MeshBuilderPolygon", because of a parser error.

There are tons more. It appears Godot changed something fundamentally important to your code.




  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:11 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:35 - Parse Error: Too many arguments for "request()" call. Expected at most 4 but received 5.
  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:35 - Parse Error: Cannot pass a value of type "bool" as "HTTPClient.Method".
  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:35 - Parse Error: Invalid argument for "request()" function: argument 3 should be "HTTPClient.Method" but is "bool".
  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:35 - Parse Error: Cannot pass a value of type "HTTPClient.Method" as "String".
  res://addons/meshbuilder/mesh_builder_communicator/mesh_builder_communicator.gd:35 - Parse Error: Invalid argument for "request()" function: argument 4 should be "String" but is "HTTPClient.Method".
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:5 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:17 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:44 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:46 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:48 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:50 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:52 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:54 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:56 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:58 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:60 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:62 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:64 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:76 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:79 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:82 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:85 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:88 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:92 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:95 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:98 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:101 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:104 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:107 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/mesh_builder_panel/mesh_builder_panel.gd:110 - Parse Error: Could not resolve class "MeshBuilder", because of a parser error.
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
  core/config/project_settings.cpp:343 - Property not found: editor_plugins/enabled
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
New Scene Root
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
  res://addons/meshbuilder/plugin.gd:9 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:10 - Parse Error: Could not resolve member "setup_and_show".
  res://addons/meshbuilder/plugin.gd:21 - Parse Error: Could not parse global class "MeshBuilder" from "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:37 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder/mesh_builder.gd".
  res://addons/meshbuilder/plugin.gd:39 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cone/mesh_builder_cone.gd".
  res://addons/meshbuilder/plugin.gd:41 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_cylinder/mesh_builder_cylinder.gd".
  res://addons/meshbuilder/plugin.gd:42 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_sphere/mesh_builder_sphere.gd".
  res://addons/meshbuilder/plugin.gd:43 - Parse Error: Could not resolve script "res://addons/meshbuilder/mesh_builder_torus/mesh_builder_torus.gd".
  scene/gui/text_edit.cpp:4959 - Index p_column = 55 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 23).

**Comment by SamuelLanders** [comment]
I think I have found one of the bigger issues. You use the following functions in your code:

# Create array meshes
	var hex_mesharr1 = []
	hex_mesharr1.resize(ArrayMesh.ARRAY_MAX)

however the latest version of Godot says:
 Invalid call. Nonexistent function 'resize' in base 'ArrayMesh'.

I have tried changing it to hex_mesharr1.resize(Mesh.ARRAY_MAX) however I am not sure if this is the correct thing to do.

**Comment by StrayEddy** [comment]
Thank you for your feedback.
I quickly updated the addon to work with Godot 4.0.1-rc3.
Please update and try it. Let me know how it goes.

**Comment by StrayEddy** [comment]
BIG changes made to the plugin. Make sure to update @SamuelLanders ;)
